package corejava.exceptionhandling;

public class UseOfThrow {

	public static int div(int a, int b) {

		int rusult = a / b;
		// throw new ArithmeticException();
		return rusult;

	}

}
